name 'sdarwin-nagios'
version '0.5.0'
dependency 'sdarwin-nrpe', '0.5.0'
dependency 'sdarwin-apache', '0.5.0'
description "Manage Nagios with Puppet."
source "https://github.com/sdarwin/Puppet-Nagios"


